apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoflow-api

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: autoflow-api

  template:
    metadata:
      labels:
        app: autoflow-api

    spec:
      containers:
        - name: autoflow-api
          image: 082229155154.dkr.ecr.us-east-2.amazonaws.com/postech/autoflowapi:${IMAGE_TAG}

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"