apiVersion: v1
kind: Secret
metadata:
  name: autoflow-db-secret

type: Opaque

stringData:
  Jwt__Secret: "SEGREDO_JWT"
  ConnectionStrings__DefaultConnection: "Server=autoflow-sqlserver.c7yk60eyi6ya.us-east-2.rds.amazonaws.com,1433;Database=AutoFlow;User Id=autoflowadmin;Password=SUA_SENHA;TrustServerCertificate=True"