# Arquivo de exemplo para documentação.
# Em produção, este Secret é criado dinamicamente pela pipeline CI/CD
# utilizando GitHub Secrets.

apiVersion: v1
kind: Secret
metadata:
  name: autoflow-db-secret

type: Opaque

stringData:
  Jwt__Secret: "SEGREDO_JWT"
  ConnectionStrings__DefaultConnection: "Server=RDS_ENDPOINT;Database=AutoFlow;User Id=autoflowadmin;Password=SUA_SENHA;TrustServerCertificate=True"