// <auto-generated />
using AutoFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810222148_Estoque")]
    partial class Estoque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoFlow.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("AutoFlow.Domain.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PecaInsumoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PecaInsumoId")
                        .IsUnique();

                    b.ToTable("Estoque", (string)null);
                });

            modelBuilder.Entity("AutoFlow.Domain.Models.PecaInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PecaInsumo", (string)null);
                });

            modelBuilder.Entity("AutoFlow.Domain.Models.Cliente", b =>
                {
                    b.OwnsOne("AutoFlow.Domain.ValueObjects.Documento", "Documento", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("int");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("varchar(14)")
                                .HasColumnName("Documento");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Cliente");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Documento")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoFlow.Domain.Models.Estoque", b =>
                {
                    b.HasOne("AutoFlow.Domain.Models.PecaInsumo", "PecaInsumo")
                        .WithOne()
                        .HasForeignKey("AutoFlow.Domain.Models.Estoque", "PecaInsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AutoFlow.Domain.ValueObjects.Comum.Quantidade", "Quantidade", b1 =>
                        {
                            b1.Property<int>("EstoqueId")
                                .HasColumnType("int");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("Quantidade");

                            b1.HasKey("EstoqueId");

                            b1.ToTable("Estoque");

                            b1.WithOwner()
                                .HasForeignKey("EstoqueId");
                        });

                    b.Navigation("PecaInsumo");

                    b.Navigation("Quantidade")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoFlow.Domain.Models.PecaInsumo", b =>
                {
                    b.OwnsOne("AutoFlow.Domain.ValueObjects.Dinheiro", "Valor", b1 =>
                        {
                            b1.Property<int>("PecaInsumoId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Valor");

                            b1.HasKey("PecaInsumoId");

                            b1.ToTable("PecaInsumo");

                            b1.WithOwner()
                                .HasForeignKey("PecaInsumoId");
                        });

                    b.Navigation("Valor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
