# CI AutoFlow
name: CI

on:
  push:
    branches:
      - feature/devops-aws

  pull_request:
    branches:
      - feature/devops-aws

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/backend

    steps:

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::082229155154:role/GitHubActionsECRPush-Techchallengepos
          aws-region: us-east-2

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependências
        run: dotnet restore AutoFlow.slnx 

      - name: Compilar projeto
        run: dotnet build AutoFlow.slnx --no-restore --configuration Release

      - name: Executar testes
        run: dotnet test AutoFlow.slnx --no-build --configuration Release

      - name: Build Docker image
        run: |
          VERSION="0.${{ github.run_number }}"

          docker build \
            -t autoflowapi:latest \
            -t autoflowapi:${VERSION} \
            -f src/AutoFlow.Api/Dockerfile \
            .