# CI AutoFlow
name: CI

on:
  push:
    branches:
      - feature/devops-aws

  pull_request:
    branches:
      - feature/devops-aws

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependências
        run: dotnet restore ./src/backend/AutoFlow.slnx 

      - name: Compilar projeto
        run: dotnet build ./src/backend/AutoFlow.slnx --no-restore --configuration Release

      - name: Executar testes
        run: dotnet test ./src/backend/AutoFlow.slnx --no-build --configuration Release