# CI AutoFlow
name: CI

on:
  push:
    branches:
      - feature/devops-aws

  pull_request:
    branches:
      - feature/devops-aws

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/backend

    steps:

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependências
        run: dotnet restore AutoFlow.slnx 

      - name: Compilar projeto
        run: dotnet build AutoFlow.slnx --no-restore --configuration Release

      - name: Executar testes
        run: dotnet test AutoFlow.slnx --no-build --configuration Release

      - name: Build Docker image
        run: |
          VERSION="0.${{ github.run_number }}"

          docker build \
            -t autoflow:latest \
            -t autoflow:${VERSION} \
            -f src/AutoFlow.Api/Dockerfile \
            .